/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["synthesize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_voices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorBody: {
            code: string;
            message: string;
        };
        HealthResponse: {
            status: string;
        };
        SynthesisRequest: {
            /**
             * Format: double
             * @description HTS all-pass constant. Omit to use the value embedded in the voice model.
             */
            alpha?: number | null;
            /**
             * Format: double
             * @description HTS postfilter coefficient.
             * @example 0
             */
            beta?: number | null;
            /**
             * Format: double
             * @description Pitch shift in semitones.
             * @example 0
             */
            pitch?: number | null;
            /**
             * Format: double
             * @example 1
             */
            speed?: number | null;
            /** @example こんにちは */
            text: string;
            /** @example mei_normal */
            voice: string;
            /**
             * Format: double
             * @description Output gain in dB.
             * @example 0
             */
            volume_db?: number | null;
        };
        VoiceDefaults: {
            /** Format: double */
            alpha: number;
            /** Format: double */
            beta: number;
            frame_period: number;
            /** Format: double */
            pitch: number;
            sampling_frequency: number;
            /** Format: double */
            speed: number;
            /** Format: double */
            volume_db: number;
        };
        VoiceInfo: {
            defaults: components["schemas"]["VoiceDefaults"];
            display_name: string;
            id: string;
            speaker: string;
            style: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    synthesize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynthesisRequest"];
            };
        };
        responses: {
            /** @description Synthesized WAV audio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": unknown;
                };
            };
            /** @description Invalid request or unknown voice */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description Synthesis failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
            /** @description TTS service unavailable or queue full */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorBody"];
                };
            };
        };
    };
    list_voices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceInfo"][];
                };
            };
        };
    };
}
